"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$hostname\
$shlvl\
$directory\
$nix_shell\

$fill\

$c\
$conda\
$crystal\
$gleam\
$golang\
$helm\
$java\
$julia\
$lua\
$nim\
$nodejs\
$php\
$pulumi\
$python\
$rlang\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$zig\

$git_state\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
$cmd_duration\
$status\
$jobs\
$line_break\
$character"""

# Disable the blank line at the start of the prompt
add_newline = true


[os]
disabled = false
format = "[](fg:#252525 bg:none)[$symbol]($style)[ ](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[shlvl]
disabled = false
format = "[](fg:#252525 bg:none)[$shlvl ](bg:#252525)[](fg:bright-green bg:#252525)[$symbol](fg:#252525 bg:bright-green)[ ](fg:bright-green bg:none)"
symbol = " "

[hostname]
disabled = false
ssh_only = true
ssh_symbol = " "
format = "[](fg:#252525 bg:none)[$hostname ](bg:#252525)[](fg:bright-purple bg:#252525)[$ssh_symbol](fg:#252525 bg:bright-purple)[ ](fg:bright-purple bg:none)"

[directory]
format = "[](fg:#252525 bg:none)[$path ]($style)[](fg:bright-blue bg:#252525)[ ](fg:#252525 bg:bright-blue)[ ](fg:bright-blue bg:none)"
style = "bg:#252525 bold"
fish_style_pwd_dir_length = 1
truncate_to_repo=false

[nix_shell]
disabled = false
format = "[](fg:#252525 bg:none)[$name ]($style)[](fg:bright-blue bg:#252525)[$symbol](fg:#252525 bg:bright-blue)[](fg:bright-blue bg:none)"
symbol = " "
style = "bg:#252525 bold"

[fill]
symbol = ' '
style = 'bold green'


[git_branch]
format = " [](fg:#252525 bg:none)[$branch ]($style)[](fg:bright-blue bg:#252525)[$symbol](fg:#252525 bg:bright-blue)[](fg:bright-blue bg:none)"
only_attached = true
style = "bg:#252525"
symbol = " "

[git_commit]
format = " [](fg:#252525 bg:none)[\\($hash\\) ]($style)[](fg:bright-blue bg:#252525)[󰜘 ](fg:#252525 bg:bright-blue)[](fg:bright-blue bg:none)"
style = "bg:#252525"

[git_status]
format = " [](fg:#252525 bg:none)[$all_status$ahead_behind ]($style)[](fg:bright-purple bg:#252525)[ ](fg:#252525 bg:bright-purple)[](fg:bright-purple bg:none)"
style = "bg:#252525"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = "󰄸 "
untracked = "?${count}"
stashed = ""
modified = "~${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = " ${count}"

[git_metrics]
disabled = false
only_nonzero_diffs = true
added_style = "bg:#252525 bold green"
deleted_style = "bg:#252525 bold red"
format = "( [](fg:#252525 bg:none)([+$added ]($added_style))([-$deleted ]($deleted_style))[](fg:yellow bg:#252525)[ ](fg:#252525 bg:yellow)[](fg:yellow bg:none))"

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "bg:#252525 bold"
format = " [](fg:#252525 bg:none)[$state( $progress_current/$progress_total) ]($style)[](fg:bright-red bg:#252525)[󱇎 ](fg:#252525 bg:bright-red)[](fg:bright-red bg:none)"

[cmd_duration]
disabled = false
min_time = 1000
format = " [](fg:#252525 bg:none)[$duration ]($style)[](fg:bright-green bg:#252525)[󱑂 ](fg:#252525 bg:bright-green)[](fg:bright-green bg:none)"
style = "bg:#252525 bold"

[status]
disabled = false
style = "bg:#252525 bold"
format = " [](fg:#252525 bg:none)[$status ]($style)[](fg:red bg:#252525)[ ](fg:#252525 bg:red)[](fg:red bg:none)"

[line_break]
disabled = false

[character]
success_symbol = "[❯](bright-blue bold)"
error_symbol = "[❯](red bold)"


#============================================================
# Languages
#============================================================

[c]
symbol = ""
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[conda]
symbol = "󰄦"
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[crystal]
symbol = ""
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[gleam]
format = "[](fg:#252525 bg:none)[$symbol]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[golang]
symbol = ""
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[helm]
symbol = "󱃾"
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[java]
symbol = ""
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[julia]
symbol = ""
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[lua]
symbol = ""
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[nim]
symbol = ""
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[nodejs]
disabled = true
symbol = ""
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[php]
symbol = ""
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[pulumi]
symbol = "⛰️"
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[python]
symbol = ""
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[rlang]
symbol = "󰟔"
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[ruby]
symbol = ""
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[rust]
symbol = ""
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[scala]
symbol = ""
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[swift]
symbol = ""
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[terraform]
symbol = ""
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"

[zig]
symbol = ""
format = "[](fg:#252525 bg:none)[$symbol ]($style)[](fg:#252525 bg:none)"
style = "bg:#252525 bold"


#============================================================
# OS Symbols
#============================================================

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "
