show=dmenu
normal_window=true
allow_images=true
insensitive=true
# Temporary workaround for this bug: https://github.com/SimplyCEO/wofi/issues/30
# hide_search=true
# height=202
height=242
width=80
prompt=Power menu
